### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by rioukevin** [inspect-js/has-symbols#11] opened 2019-12-26 10:06 UTC
Hello,

I use vuepress (Vuejs) that use library using has-symbols, an error occured:
`global is not defined` in the library script

```javascript
'use strict';

// V Error is throw next line V
var origSymbol = global.Symbol;
var hasSymbolSham = require('./shams');

module.exports = function hasNativeSymbols() {
	if (typeof origSymbol !== 'function') { return false; }
	if (typeof Symbol !== 'function') { return false; }
	if (typeof origSymbol('foo') !== 'symbol') { return false; }
	if (typeof Symbol('bar') !== 'symbol') { return false; }

	return hasSymbolSham();
};
```

So to correct it, I add in my scripts 
```javascript
window.global = window
```

I see that this error is throwed with angular also, so it looks that more and more framework doesn't support global 😉 

Can you add a check on window.global to avoid create an error when it isn't define ? 
Just emit a default value when not defined ? 

Thank you 😃 😄 

Have a nice day and be happy !
Kévin

**Comment by ljharb** [comment] 2019-12-26 16:20
global is always defined in node, this is a node module, and bundlers should be transforming globsl to window for browsers.

If your bundler isn’t doing that, please file an issue on it so it can be fixed.

**Comment by ljharb** [comment] 2019-12-26 16:20
Duplicate of #6. Duplicate of #4.

**Comment by ljharb** [comment] 2021-02-26 03:37
@JounQin `global` is a browser-friendly check in a node module, when used with a non-broken node module bundler.

This package is a node module, and is explicitly not intended to be used anywhere but in node, or in a browser via a properly working node module bundler - which requires that it support `global`, among a number of other things.

**Comment by JounQin** [comment] 2021-02-26 04:03
Maybe you're right, but by just adding `typeof Symbol !== 'undefined' && Symbol`, a lot of issues will be resolved thanks to this package.

**Comment by ljharb** [comment] 2021-02-27 16:29
All that would achieve is to make it slightly easier for bundlers to do the wrong thing. You'll still find yourself suffering due to another package - it'd just move the problem.

That said, it's fair that the typeof version would work identically, so I suppose I'll go ahead and do it. I strongly suggest you also spend effort trying to fix the broken node module bundlers that fail to polyfill `global`.

**Closed** 2021-02-27 16:30 UTC
